theme: jekyll-theme-minimal
title: Garrett Mulcahy
description: Here is my personal website to see what projects I have been up to! 
avatar: https://avatars0.githubusercontent.com/u/42593890?s=460&u=084f730b87e299217924bd4bb206ef48fe377479&v=4
